name: Docker Python Package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t my-python-app .

      - name: Run tests in Docker container
        run: |
          docker run --rm my-python-app pytest tests.py --doctest-modules --junitxml=junit/test-results.xml

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results
          path: junit/test-results.xml

      - name: Lint code with Ruff
        run: |
          docker run --rm -v ${{ github.workspace }}:/usr/src/app my-python-app bash -c "pip install ruff && ruff check --output-format=github --target-version=py39"
